wandb_version: 1

_wandb:
  desc: null
  value:
    cli_version: 0.10.23
    framework: tensorflow
    is_jupyter_run: true
    is_kaggle_kernel: false
    python_version: 2.7.17
    t:
      1:
      - 3
      4: 2.7.17
      5: 0.10.23
      8:
      - 1
learning_rate:
  desc: null
  value: 0.001
